# Generated by Django 5.0.3 on 2024-11-02 17:43

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Open',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open', models.CharField(choices=[('باز', 'باز'), ('بسته', 'بسته')], max_length=25, verbose_name='وضعیت باز بودن : ')),
                ('shomare', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='sefaresh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tedad', models.SmallIntegerField(verbose_name='نعداد لباس')),
                ('name', models.CharField(max_length=80, verbose_name='نام و نام خانوادگی')),
                ('shomare', models.BigIntegerField(verbose_name='شماره تماس')),
                ('created', django_jalali.db.models.jDateField(auto_now_add=True, verbose_name='تاریخ سفارش')),
                ('vaziat', models.CharField(choices=[('در حال شست و شو', 'در حال شست و شو'), ('اماده ی تحویل', 'اماده ی تحویل'), ('تحویل مشتری داده شد', 'تحویل مشتری داده شد')], default='در حال شست و شو', max_length=30, verbose_name='وضعیت سفارش:')),
            ],
        ),
    ]
