# Generated by Django 5.0.3 on 2024-08-27 17:07

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sefaresh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('famili', models.CharField(max_length=25)),
                ('shomare', models.IntegerField()),
                ('created', django_jalali.db.models.jDateField()),
            ],
        ),
    ]
