# Generated by Django 5.0.3 on 2024-08-27 17:09

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sefaresh',
            name='created',
            field=django_jalali.db.models.jDateField(auto_now=True),
        ),
    ]
