# Generated by Django 5.0.3 on 2024-11-03 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sefaresh',
            name='vaziat',
            field=models.CharField(choices=[('اماده ی تحویل', 'اماده ی تحویل'), ('در حال شست و شو', 'در حال شست و شو'), ('تحویل مشتری داده شد', 'تحویل مشتری داده شد')], default='در حال شست و شو', max_length=30, verbose_name='وضعیت سفارش:'),
        ),
    ]
