# Generated by Django 5.0.3 on 2024-08-27 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_sefaresh_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sefaresh',
            name='shomare',
            field=models.BigIntegerField(),
        ),
    ]
