# Generated by Django 5.0.3 on 2024-08-27 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_sefaresh_shomare'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sefaresh',
            name='famili',
        ),
        migrations.AlterField(
            model_name='sefaresh',
            name='name',
            field=models.CharField(max_length=80),
        ),
    ]
