# Generated by Django 5.1 on 2024-08-27 18:28

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_sefaresh_famili_alter_sefaresh_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sefaresh',
            name='created',
            field=django_jalali.db.models.jDateField(auto_now=True, verbose_name='تاریخ سفارش'),
        ),
        migrations.AlterField(
            model_name='sefaresh',
            name='name',
            field=models.CharField(max_length=80, verbose_name='نام و نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='sefaresh',
            name='shomare',
            field=models.BigIntegerField(verbose_name='شماره تماس '),
        ),
    ]
