# Generated by Django 5.0.3 on 2024-08-28 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_sefaresh_created_alter_sefaresh_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sefaresh',
            name='vaziat',
            field=models.CharField(default='0', max_length=30, verbose_name='وضعیت سفارش :'),
        ),
    ]
