# Generated by Django 5.0.3 on 2024-08-28 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='open',
            name='open',
            field=models.CharField(choices=[('open', 'باز'), ('close', 'بسته')], default=0, max_length=25, verbose_name='وضعیت باز بودن : '),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sefaresh',
            name='vaziat',
            field=models.CharField(choices=[('0', 'تحویل گرفته شد'), ('1', 'اماده ی تحویل')], default='0', max_length=30, verbose_name='وضعیت سفارش :'),
        ),
    ]
