# Generated by Django 5.0.3 on 2024-08-28 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_open_open_alter_sefaresh_vaziat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='open',
            name='open',
            field=models.CharField(choices=[('باز', 'باز'), ('بسته', 'بسته')], max_length=25, verbose_name='وضعیت باز بودن : '),
        ),
    ]
