# Generated by Django 5.0.3 on 2024-08-28 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_open_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='open',
            name='shomare',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='open',
            name='open',
            field=models.CharField(choices=[('بسته', 'بسته'), ('باز', 'باز')], max_length=25, verbose_name='وضعیت باز بودن : '),
        ),
        migrations.AlterField(
            model_name='sefaresh',
            name='vaziat',
            field=models.CharField(choices=[('1', 'اماده ی تحویل'), ('0', 'تحویل گرفته شد')], default='0', max_length=30, verbose_name='وضعیت سفارش :'),
        ),
    ]
