# Generated by Django 5.0.3 on 2024-08-28 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_alter_open_open'),
    ]

    operations = [
        migrations.AlterField(
            model_name='open',
            name='open',
            field=models.CharField(choices=[('بسته', 'بسته'), ('باز', 'باز')], max_length=25, verbose_name='وضعیت باز بودن : '),
        ),
    ]
