# Generated by Django 5.0.3 on 2024-08-29 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_open_open'),
    ]

    operations = [
        migrations.AlterField(
            model_name='open',
            name='open',
            field=models.CharField(choices=[('باز', 'باز'), ('بسته', 'بسته')], max_length=25, verbose_name='وضعیت باز بودن : '),
        ),
        migrations.AlterField(
            model_name='sefaresh',
            name='vaziat',
            field=models.CharField(choices=[('0', 'در حال شست و شو'), ('1', 'اماده ی تحویل'), ('2', 'تحویل مشتری داده شد')], default='0', max_length=30, verbose_name='وضعیت سفارش :'),
        ),
    ]
