# Generated by Django 5.0.3 on 2024-08-29 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_alter_open_open_alter_sefaresh_vaziat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='open',
            name='open',
            field=models.CharField(choices=[('بسته', 'بسته'), ('باز', 'باز')], max_length=25, verbose_name='وضعیت باز بودن : '),
        ),
        migrations.AlterField(
            model_name='sefaresh',
            name='vaziat',
            field=models.CharField(choices=[('اماده ی تحویل', '1'), ('در حال شست و شو ', '0'), ('تحویل مشتری داده شد', '2')], default='0', max_length=30, verbose_name='وضعیت سفارش :'),
        ),
    ]
