# Generated by Django 5.0.3 on 2024-08-29 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_alter_open_open_alter_sefaresh_vaziat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sefaresh',
            name='shomare',
            field=models.BigIntegerField(verbose_name='شماره تماس'),
        ),
        migrations.AlterField(
            model_name='sefaresh',
            name='vaziat',
            field=models.CharField(choices=[('در حال شست و شو', 'در حال شست و شو'), ('تحویل مشتری داده شد', 'تحویل مشتری داده شد'), ('اماده ی تحویل', 'اماده ی تحویل')], default='در حال شست و شو', max_length=30, verbose_name='وضعیت سفارش:'),
        ),
    ]
