# Generated by Django 5.0.3 on 2024-08-29 16:44

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_alter_sefaresh_shomare_alter_sefaresh_vaziat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sefaresh',
            name='created',
            field=django_jalali.db.models.jDateField(auto_now_add=True, verbose_name='تاریخ سفارش'),
        ),
        migrations.AlterField(
            model_name='sefaresh',
            name='vaziat',
            field=models.CharField(choices=[('تحویل مشتری داده شد', 'تحویل مشتری داده شد'), ('در حال شست و شو', 'در حال شست و شو'), ('اماده ی تحویل', 'اماده ی تحویل')], default='در حال شست و شو', max_length=30, verbose_name='وضعیت سفارش:'),
        ),
    ]
