# Generated by Django 5.0.3 on 2024-08-30 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_alter_sefaresh_created_alter_sefaresh_vaziat'),
    ]

    operations = [
        migrations.AddField(
            model_name='sefaresh',
            name='tedad',
            field=models.SmallIntegerField(default=0, verbose_name='نعداد لباس'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='open',
            name='open',
            field=models.CharField(choices=[('بسته', 'بسته'), ('باز', 'باز')], max_length=25, verbose_name='وضعیت باز بودن : '),
        ),
        migrations.AlterField(
            model_name='sefaresh',
            name='vaziat',
            field=models.CharField(choices=[('در حال شست و شو', 'در حال شست و شو'), ('اماده ی تحویل', 'اماده ی تحویل'), ('تحویل مشتری داده شد', 'تحویل مشتری داده شد')], default='در حال شست و شو', max_length=30, verbose_name='وضعیت سفارش:'),
        ),
    ]
